### ISSUE TITLE
Simplify _scrollActiveEditorToEnd()

### ISSUE THREAD

**Issue by ArturoDent** [foxx1337/autoscrolldown#1]
```
private _scrollActiveEditorToEnd() {
        const editor = vscode.window.activeTextEditor;
        const lineCount = editor.document.lineCount;
        const range = editor.document.lineAt(lineCount - 1).range;
        editor.selection = new vscode.Selection(range.end, range.end);
        editor.revealRange(range);
    }
```

Perhaps you could simplify the actual scroll with the complex command 

> editorScroll - Scroll editor in the given direction
> 
> Editor scroll argument object
> Property-value pairs that can be passed through this argument:
>   'to': A mandatory direction value.
>   'up', 'down'
>   'by': Unit to move. Default is computed based on 'to' value.
>   'line', 'wrappedLine', 'page', 'halfPage'
>   'value': Number of units to move. Default is '1'.
>   'revealCursor': If 'true' reveals the cursor if it is outside view port.

since you have the lineNumber/lineCount

From [https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands](url)

**Comment by foxx1337** [comment]
Hi,

I'm not entirely sure this method is what I need.

I'm also trying to deselect the current selection (as it extends with the document growing from external changes), then move the cursor to the end of the document and then scroll until said position is in view.

This `vscode.commands.executeCommand("editorScroll")` seems to only partially help with these operations, or maybe I can't figure out how to correctly use it.
