### ISSUE TITLE
Only works when Visual Studio Code 1.25 is unfocused

### ISSUE THREAD

**Issue by antcodd** [foxx1337/autoscrolldown#2]
Auto scrolling only seems to be working on VSCode 1.25 Linux when the entire visual studio code window is unfocused, despite the indicator in the status bar. At first I thought the extension wasn't working.

It might make sense if it was the editor that had to be unfocused, but it seems to be the entire visual studio code window.

```
{
    "autoscrolldown.allFiles": true,
    "autoscrolldown.onlyWhenAtEnd": true
}
```

Thanks for the terminal style one line scrolling, much nicer than the other similar extension.

**Comment by foxx1337** [comment]
Hmm, I'll check this out since I haven't tested the functionality on Linux yet. It does work on Windows, since I'm using it even now.

Your settings look fine, by the way.

**Comment by foxx1337** [comment]
I managed to reproduce the behavior you're reporting and you're absolutely right. [It's even by (very bad) design as it is!](https://github.com/foxx1337/autoscrolldown/blob/master/src/extension.ts#L97)
