### ISSUE TITLE
1.2 version scrolls down when changing tabs and editing internally

### ISSUE THREAD

**Issue by TechHypno** [foxx1337/autoscrolldown#6]
Reproduce Steps:
1. have 2 documents open in 2 tabs in 1 editor
2. click the inactive tab
3. edit the document in any way in the editor
4. edit takes effect and immiediately autoscrolldown triggers and puts the cursor at the bottom of the document.
This happens once after every tab switch.

![image](https://user-images.githubusercontent.com/64381479/133952783-9a3bc499-d36a-4640-9148-9c7233f8976f.png)

**Comment by TechHypno** [comment]
vscode autoscrolldown settings
![image](https://user-images.githubusercontent.com/64381479/133952783-9a3bc499-d36a-4640-9148-9c7233f8976f.png)

**Comment by foxx1337** [comment]
Got it, working on a fix in 1.2.1 - might be a bit tricky. Check the "Only When At End" in the meanwhile and make sure you press Ctrl+End in documents you want to scroll automatically.

**Comment by foxx1337** [comment]
Released the fix. It's impossible to differentiate by cause of change (external versus user) with the vscode API, so when `onlyWhenAtEnd` is `false` I'm not autoscrolling externally modified documents upon switching to their tabs. That functionality I introduced in 1.2.0 will only work for `onlyWhenAtEnd = true`.
